config/routes.rb
Rails.application.routes.draw do
  resources :schedulers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'schedulers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scheduler.rb
class Scheduler < ApplicationRecord
  # VALIDATIONS
  validates :fixed_datetime, presence: true

  # CLASS METHODS
  class << self
    def no_repetition
      where.not(repeat_unit: SchedulerConstants::RepeatUnit::NONE)
    end

    def has_run
      where.not('number_of_runs = ?', 0)
    end
  end

  # INSTANCE METHODS
  def compute_fixed_time input_params
    dummy = '**'
    datetime = ''
    input_params = case repeat_unit
      when SchedulerConstants::RepeatUnit::YEARLY
        input_params.slice(:month, :day, :hour, :minute)
      when SchedulerConstants::RepeatUnit::MONTHLY
        input_params.slice(:day, :hour, :minute)
      when SchedulerConstants::RepeatUnit::DAILY
        input_params.slice(:hour, :minute)
      when SchedulerConstants::RepeatUnit::HOURLY
        input_params.slice(:minute)
      when SchedulerConstants::RepeatUnit::MINUTES
        input_params.slice()
      else
        input_params
      end
    datetime += "#{get_datetime_str(input_params[:year], dummy * 2)}-"
    datetime += "#{get_datetime_str(input_params[:month], dummy)}-"
    datetime += "#{get_datetime_str(input_params[:day], dummy)} "
    datetime += "#{get_datetime_str(input_params[:hour], dummy)}:"
    datetime += get_datetime_str(input_params[:minute], dummy)
    fixed_datetime = datetime
  end

  def reset_history
    if number_of_runs > 0
      update_attributes(last_run_at: nil, number_of_runs: 0)
    end
  end

  # PRIVATE METHODS
  private
    def get_datetime_str input_hash_val, dummy_val
      input_hash_val ? "#{format_digits(input_hash_val)}" : dummy_val
    end

    def format_digits number
      number.to_i < 10 ? "0#{number}" : number
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected
    def get_js_variables options = {}
      if options[:repeat_units]
        gon.repeat_units = {
          none: SchedulerConstants::RepeatUnit::NONE,
          yearly: SchedulerConstants::RepeatUnit::YEARLY,
          monthly: SchedulerConstants::RepeatUnit::MONTHLY,
          daily: SchedulerConstants::RepeatUnit::DAILY,
          hourly: SchedulerConstants::RepeatUnit::HOURLY,
          minutes: SchedulerConstants::RepeatUnit::MINUTES
        }
      end
    end
end

app/controllers/schedulers_controller.rb
class SchedulersController < ApplicationController
  before_action :set_scheduler, only: [:show, :edit, :update, :destroy]

  # GET /schedulers
  # GET /schedulers.json
  def index
    @schedulers = Scheduler.all
  end

  # GET /schedulers/1
  # GET /schedulers/1.json
  def show
  end

  # GET /schedulers/new
  def new
    @scheduler = Scheduler.new
    get_js_variables(repeat_units: true)
  end

  # GET /schedulers/1/edit
  def edit
    get_js_variables(repeat_units: true)
  end

  # POST /schedulers
  # POST /schedulers.json
  def create
    @scheduler = Scheduler.new(scheduler_params)
    get_js_variables(fixed_datetime_regex: true)

    respond_to do |format|
      @scheduler.fixed_datetime = @scheduler.compute_fixed_time(params.slice(:year, :month, :day, :hour, :minute))
      if @scheduler.save
        format.html { redirect_to @scheduler, notice: 'Scheduler was successfully created.' }
        format.json { render :show, status: :created, location: @scheduler }
      else
        format.html { render :new }
        format.json { render json: @scheduler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedulers/1
  # PATCH/PUT /schedulers/1.json
  def update
    get_js_variables(fixed_datetime_regex: true)
    respond_to do |format|
      @scheduler.fixed_datetime = @scheduler.compute_fixed_time(params.slice(:year, :month, :day, :hour, :minute))
      @scheduler.assign_attributes(scheduler_params)
      has_changed = @scheduler.changed?
      if @scheduler.save
        @scheduler.reset_history if has_changed
        format.html { redirect_to @scheduler, notice: 'Scheduler was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduler }
      else
        format.html { render :edit }
        format.json { render json: @scheduler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedulers/1
  # DELETE /schedulers/1.json
  def destroy
    @scheduler.destroy
    respond_to do |format|
      format.html { redirect_to schedulers_url, notice: 'Scheduler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduler
      @scheduler = Scheduler.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduler_params
      params.require(:scheduler).permit(:repeat_unit, :repeat_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedulers_helper.rb
module SchedulersHelper
  def get_repeat_unit_options
    options = []
    SchedulerConstants::RepeatUnit::ALL.each do |key, value|
      options << [key.titlecase, value]
    end
    return options
  end

  def get_repeat_num_options repeat_unit
    options = []
    case repeat_unit
    when SchedulerConstants::RepeatUnit::YEARLY
      (1..5).map{ |year| options << [year, year] }
    when SchedulerConstants::RepeatUnit::MONTHLY
      (1..11).map{ |month| options << [month, month] }
    when SchedulerConstants::RepeatUnit::DAILY
      (1..30).map{ |day| options << [day, day] }
    when SchedulerConstants::RepeatUnit::HOURLY
      (1..23).map{ |hour| options << [hour, hour] }
    when SchedulerConstants::RepeatUnit::MINUTES
      (5..55).step(5).map{ |minute| options << [minute, minute] }
    end
    return options
  end

  def get_datetime datetime
    datetime ? datetime.strftime('%d-%m-%Y %I:%M %p %Z') : 'Not yet run!'
  end

  def get_fix_time_options dropdown_for, db_value
    options = []
    case dropdown_for
      when :year
        year_now = Time.zone.now.year
        (year_now..(year_now + 5)).map{ |year| options << [year, year] }
      when :month
        (1..12).map{ |month| options << [month, month] }
      when :day
        (1..31).map{ |day| options << [day, day] }
      when :hour
        (0..23).map{ |hour| options << [hour, hour] }
      when :minute
        (0..59).step(5).map{ |minute| options << [minute, minute] }
    end
    return options
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = SchedulerConstants::Application::NAME
    = csrf_meta_tags
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .container
      = yield

app/views/schedulers/_form.html.slim
= form_for(scheduler) do |f|
  - if scheduler.errors.any?
    #error_explanation
      h2
        = pluralize(scheduler.errors.count, "error")
        | prohibited this scheduler from being saved:
      ul
        - scheduler.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :repeat_unit
    = f.select :repeat_unit, options_for_select(get_repeat_unit_options, scheduler.repeat_unit)
  .field#repeatNum data-selected-unit=scheduler.repeat_unit data-selected-number=scheduler.repeat_number
    = f.label :repeat_number
    = f.select :repeat_number, options_for_select(  \
      get_repeat_num_options(scheduler.repeat_unit),\
      scheduler.repeat_number)
  .field#fixedDatetime data-fixed-datetime=scheduler.fixed_datetime
    = f.label :fixed_datetime
    = select_tag :year, options_for_select(get_fix_time_options :year, scheduler.fixed_datetime), id: :fixedYear
    = select_tag :month, options_for_select(get_fix_time_options :month, scheduler.fixed_datetime), id: :fixedMonth
    = select_tag :day, options_for_select(get_fix_time_options :day, scheduler.fixed_datetime), id: :fixedDay
    = " - "
    = select_tag :hour, options_for_select(get_fix_time_options :hour, scheduler.fixed_datetime), id: :fixedHour
    = " : "
    = select_tag :minute, options_for_select(get_fix_time_options :minute, scheduler.fixed_datetime), id: :fixedMinute
  .help-text
    strong Meaning: &nbsp;
    span#helpText
    span#testArea
  .actions
    = f.submit

app/views/schedulers/edit.html.slim
h1 Editing Scheduler
= render 'form', scheduler: @scheduler
= link_to 'Show', @scheduler
|&nbsp;|&nbsp;
= link_to 'Back', schedulers_path

app/views/schedulers/index.html.slim
p#notice= notice
h1 Schedulers
table border=1 cellpadding=5
  thead
    tr
      th Repeat unit
      th Repeat number
      th Fixed datetime
      th Last run at
      th Number of times run
      th colspan="3" Actions
  tbody
    - if @schedulers.count > 0
      - @schedulers.each do |scheduler|
        tr
          td = SchedulerConstants::RepeatUnit::ALL.invert[scheduler.repeat_unit].titlecase
          td = scheduler.repeat_number ? scheduler.repeat_number : 'NA'
          td = scheduler.fixed_datetime
          td = get_datetime scheduler.last_run_at
          td = scheduler.number_of_runs
          td = link_to 'Show', scheduler
          td = link_to 'Edit', edit_scheduler_path(scheduler)
          td = link_to 'Destroy', scheduler, method: :delete, data: {confirm: 'Are you sure?'}
    - else
      tr
        td.center colspan='8' There are no schedules yet! Create one by clicking the below link.
br/
= link_to 'New Scheduler', new_scheduler_path

app/views/schedulers/new.html.slim
h1 New Scheduler
= render 'form', scheduler: @scheduler
= link_to 'Back', schedulers_path

app/views/schedulers/show.html.slim
p#notice= notice
p
  strong Repeat unit:
  = SchedulerConstants::RepeatUnit::ALL.invert[@scheduler.repeat_unit].titlecase
p
  strong Repeat number:
  = @scheduler.repeat_number
p
  strong Fixed datetime:
  = @scheduler.fixed_datetime
p
  strong Last run at:
  = get_datetime @scheduler.last_run_at
p
  strong Number of runs:
  = @scheduler.number_of_runs
= link_to 'Edit', edit_scheduler_path(@scheduler)
| \
= link_to 'Back', schedulers_path